"""Build src/state_lookup.py: every real US zip (five digits) -> state code.

Source: GeoNames postal-code files, https://download.geonames.org/export/zip/
  US.zip              -> state is column 5 (admin1 code)
  PR, VI, GU, AS, MP  -> state is column 1 (country code); column 5 there is a county code
Rows with a blank state are skipped. GeoNames lists only some military APO/FPO zips (with a
blank state), so military zips are not in the table at all: src/main.py resolves a complete
five-digit zip in a military-only prefix (MILITARY_PREFIX, written below) to AE, AA or AP.

Usage: python tools/generate_state_lookup.py   (writes src/state_lookup.py)
"""
import csv
import io
import os
import urllib.request
import zipfile

BASE = "https://download.geonames.org/export/zip/"
TERRITORIES = ["PR", "VI", "GU", "AS", "MP"]
MILITARY = {**{f"09{d}": "AE" for d in "0123456789"}, "340": "AA",
            **{f"96{d}": "AP" for d in "23456"}}
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "state_lookup.py")


def rows(code):
    raw = urllib.request.urlopen(BASE + code + ".zip", timeout=60).read()
    with zipfile.ZipFile(io.BytesIO(raw)) as z:
        text = z.read(code + ".txt").decode("utf-8")
    return list(csv.reader(io.StringIO(text), delimiter="\t"))


def build():
    table = {}
    counts = {}
    for code in ["US"] + TERRITORIES:
        n = 0
        for r in rows(code):
            zip5 = r[1]
            if len(zip5) != 5 or not zip5.isdigit():
                continue
            state = r[4] if code == "US" else r[0]
            if not state:
                continue
            if zip5 in table and table[zip5] != state:
                raise SystemExit(f"conflicting state for {zip5}: {table[zip5]} vs {state}")
            table[zip5] = state
            n += 1
        counts[code] = n
    return table, counts


def main():
    table, counts = build()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/generate_state_lookup.py from GeoNames postal codes.\n")
        f.write("# " + ", ".join(f"{k} {v}" for k, v in counts.items()) + f"; {len(table)} zips.\n")
        f.write("# Five-digit zip -> state. A zip not in this table has no state.\n\n")
        f.write("STATE_BY_ZIP5 = {\n")
        for zip5 in sorted(table):
            f.write(f"    '{zip5}': '{table[zip5]}',\n")
        f.write("}\n\n")
        f.write("# USPS military-only prefixes. Only a complete five-digit zip is ever matched.\n")
        f.write("MILITARY_PREFIX = {\n")
        for p in sorted(MILITARY):
            f.write(f"    '{p}': '{MILITARY[p]}',\n")
        f.write("}\n")
    print(f"wrote {OUT}: {len(table)} zips ({counts})")


if __name__ == "__main__":
    main()
