VAMC_LOOKUP = {
    '006': 'San Juan VA Medical Center, PR',
    '007': 'San Juan VA Medical Center, PR',
    '008': 'San Juan VA Medical Center, PR',
    '009': 'San Juan VA Medical Center, PR',
    '010': 'Edward P. Boland VAMC, MA',
    '011': 'Edward P. Boland VAMC, MA',
    '012': 'Edward P. Boland VAMC, MA',
    '013': 'Edward P. Boland VAMC, MA',
    '014': 'Edward P. Boland VAMC, MA',
    '016': 'Edward P. Boland VAMC, MA',
    '017': 'Edith Nourse Rogers VAMC, MA',
    '018': 'Edith Nourse Rogers VAMC, MA',
    '019': 'Edith Nourse Rogers VAMC, MA',
    '021': 'Jamaica Plain VAMC, MA',
    '023': 'Jamaica Plain VAMC, MA',
    '024': 'Jamaica Plain VAMC, MA',
    '026': 'Providence VA Medical Center, RI',
    '027': 'Providence VA Medical Center, RI',
    '028': 'Providence VA Medical Center, RI',
    '029': 'Providence VA Medical Center, RI',
    '030': 'Manchester VA Medical Center, NH',
    '031': 'Manchester VA Medical Center, NH',
    '032': 'Manchester VA Medical Center, NH',
    '034': 'White River Junction VAMC, VT',
    '035': 'White River Junction VAMC, VT',
    '038': 'Manchester VA Medical Center, NH',
    '041': 'Togus VA Medical Center, ME',
    '042': 'Togus VA Medical Center, ME',
    '043': 'Togus VA Medical Center, ME',
    '044': 'Togus VA Medical Center, ME',
    '046': 'Togus VA Medical Center, ME',
    '047': 'Togus VA Medical Center, ME',
    '050': 'White River Junction VAMC, VT',
    '052': 'White River Junction VAMC, VT',
    '053': 'White River Junction VAMC, VT',
    '054': 'White River Junction VAMC, VT',
    '057': 'White River Junction VAMC, VT',
    '058': 'White River Junction VAMC, VT',
    '060': 'West Haven VA Medical Center, CT',
    '061': 'West Haven VA Medical Center, CT',
    '062': 'West Haven VA Medical Center, CT',
    '063': 'West Haven VA Medical Center, CT',
    '064': 'West Haven VA Medical Center, CT',
    '065': 'West Haven VA Medical Center, CT',
    '067': 'West Haven VA Medical Center, CT',
    '068': 'West Haven VA Medical Center, CT',
    '069': 'West Haven VA Medical Center, CT',
    '070': 'East Orange VA Medical Center, NJ',
    '073': 'East Orange VA Medical Center, NJ',
    '075': 'East Orange VA Medical Center, NJ',
    '076': 'East Orange VA Medical Center, NJ',
    '077': 'East Orange VA Medical Center, NJ',
    '078': 'East Orange VA Medical Center, NJ',
    '079': 'East Orange VA Medical Center, NJ',
    '080': 'Corporal M. J. Crescenz VAMC, PA',
    '081': 'Corporal M. J. Crescenz VAMC, PA',
    '082': 'Wilmington VA Medical Center, DE',
    '083': 'Wilmington VA Medical Center, DE',
    '086': 'East Orange VA Medical Center, NJ',
    '087': 'East Orange VA Medical Center, NJ',
    '088': 'East Orange VA Medical Center, NJ',
    '100': 'Margaret C. Corbin VA Campus, NY',
    '103': 'Margaret C. Corbin VA Campus, NY',
    '104': 'James J. Peters VAMC, NY',
    '105': 'Franklin D. Roosevelt Hospital, NY',
    '106': 'James J. Peters VAMC, NY',
    '107': 'James J. Peters VAMC, NY',
    '109': 'Franklin D. Roosevelt Hospital, NY',
    '111': 'James J. Peters VAMC, NY',
    '112': 'Margaret C. Corbin VA Campus, NY',
    '114': 'Margaret C. Corbin VA Campus, NY',
    '115': 'Northport VA Medical Center, NY',
    '117': 'Northport VA Medical Center, NY',
    '119': 'Northport VA Medical Center, NY',
    '120': 'Buffalo VA Medical Center, NY',
    '122': 'Buffalo VA Medical Center, NY',
    '123': 'Buffalo VA Medical Center, NY',
    '124': 'Buffalo VA Medical Center, NY',
    '125': 'Franklin D. Roosevelt Hospital, NY',
    '126': 'Franklin D. Roosevelt Hospital, NY',
    '127': 'Franklin D. Roosevelt Hospital, NY',
    '128': 'Buffalo VA Medical Center, NY',
    '129': 'Buffalo VA Medical Center, NY',
    '130': 'Buffalo VA Medical Center, NY',
    '131': 'Buffalo VA Medical Center, NY',
    '132': 'Buffalo VA Medical Center, NY',
    '134': 'Buffalo VA Medical Center, NY',
    '136': 'Buffalo VA Medical Center, NY',
    '138': 'Buffalo VA Medical Center, NY',
    '139': 'Buffalo VA Medical Center, NY',
    '140': 'Buffalo VA Medical Center, NY',
    '142': 'Buffalo VA Medical Center, NY',
    '143': 'Buffalo VA Medical Center, NY',
    '144': 'Buffalo VA Medical Center, NY',
    '146': 'Buffalo VA Medical Center, NY',
    '147': 'Buffalo VA Medical Center, NY',
    '148': 'Buffalo VA Medical Center, NY',
    '149': 'Buffalo VA Medical Center, NY',
    '150': 'Pittsburgh VAMC University Dr., PA',
    '151': 'Pittsburgh VAMC University Dr., PA',
    '152': 'Pittsburgh VAMC University Dr., PA',
    '153': 'Pittsburgh VAMC University Dr., PA',
    '154': 'Pittsburgh VAMC University Dr., PA',
    '156': 'Pittsburgh VAMC University Dr., PA',
    '157': 'James E. Van Zandt VAMC, PA',
    '158': 'James E. Van Zandt VAMC, PA',
    '159': 'James E. Van Zandt VAMC, PA',
    '160': 'Abie Abraham VA Clinic, PA',
    '161': 'Abie Abraham VA Clinic, PA',
    '162': 'Abie Abraham VA Clinic, PA',
    '163': 'Erie VA Medical Center, PA',
    '165': 'Erie VA Medical Center, PA',
    '166': 'James E. Van Zandt VAMC, PA',
    '167': 'Erie VA Medical Center, PA',
    '168': 'James E. Van Zandt VAMC, PA',
    '169': 'Buffalo VA Medical Center, NY',
    '170': 'Lebanon VA Medical Center, PA',
    '174': 'Lebanon VA Medical Center, PA',
    '175': 'Lebanon VA Medical Center, PA',
    '177': 'Wilkes-Barre VA Medical Center, PA',
    '178': 'Wilkes-Barre VA Medical Center, PA',
    '179': 'Lebanon VA Medical Center, PA',
    '180': 'Wilkes-Barre VA Medical Center, PA',
    '181': 'Wilkes-Barre VA Medical Center, PA',
    '184': 'Wilkes-Barre VA Medical Center, PA',
    '187': 'Wilkes-Barre VA Medical Center, PA',
    '188': 'Wilkes-Barre VA Medical Center, PA',
    '190': 'Coatesville VA Medical Center, PA',
    '191': 'Corporal M. J. Crescenz VAMC, PA',
    '193': 'Coatesville VA Medical Center, PA',
    '194': 'Coatesville VA Medical Center, PA',
    '196': 'Lebanon VA Medical Center, PA',
    '198': 'Wilmington VA Medical Center, DE',
    '199': 'Wilmington VA Medical Center, DE',
    '200': 'Washington VA Medical Center, DC',
    '203': 'Washington VA Medical Center, DC',
    '204': 'Washington VA Medical Center, DC',
    '206': 'Washington VA Medical Center, DC',
    '207': 'Baltimore VA Medical Center, MD',
    '208': 'Washington VA Medical Center, DC',
    '210': 'Baltimore VA Medical Center, MD',
    '212': 'Baltimore VA Medical Center, MD',
    '214': 'Baltimore VA Medical Center, MD',
    '215': 'Martinsburg VA Medical Center, WV',
    '216': 'Baltimore VA Medical Center, MD',
    '217': 'Martinsburg VA Medical Center, WV',
    '218': 'Baltimore VA Medical Center, MD',
    '219': 'Baltimore VA Medical Center, MD',
    '220': 'Washington VA Medical Center, DC',
    '221': 'Washington VA Medical Center, DC',
    '223': 'Washington VA Medical Center, DC',
    '224': 'Richmond VA Medical Center, VA',
    '226': 'Martinsburg VA Medical Center, WV',
    '228': 'Martinsburg VA Medical Center, WV',
    '229': 'Richmond VA Medical Center, VA',
    '232': 'Richmond VA Medical Center, VA',
    '233': 'Hampton VA Medical Center, VA',
    '234': 'Hampton VA Medical Center, VA',
    '236': 'Hampton VA Medical Center, VA',
    '237': 'Hampton VA Medical Center, VA',
    '238': 'Richmond VA Medical Center, VA',
    '241': 'Salem VA Medical Center, VA',
    '242': 'James H. Quillen VAMC, TN',
    '243': 'Salem VA Medical Center, VA',
    '244': 'Salem VA Medical Center, VA',
    '245': 'Salem VA Medical Center, VA',
    '246': 'James H. Quillen VAMC, TN',
    '247': 'Beckley VA Medical Center, WV',
    '249': 'Beckley VA Medical Center, WV',
    '253': 'Hershel Woody Williams VAMC, WV',
    '254': 'Martinsburg VA Medical Center, WV',
    '256': 'Hershel Woody Williams VAMC, WV',
    '257': 'Hershel Woody Williams VAMC, WV',
    '258': 'Beckley VA Medical Center, WV',
    '261': 'Louis A. Johnson VAMC, WV',
    '262': 'Louis A. Johnson VAMC, WV',
    '263': 'Louis A. Johnson VAMC, WV',
    '265': 'Louis A. Johnson VAMC, WV',
    '266': 'Louis A. Johnson VAMC, WV',
    '268': 'Martinsburg VA Medical Center, WV',
    '272': 'W.G. Hefner Salisbury VAMC, NC',
    '273': 'Fayetteville VA Medical Center, NC',
    '275': 'Durham VA Medical Center, NC',
    '276': 'Durham VA Medical Center, NC',
    '277': 'Durham VA Medical Center, NC',
    '278': 'Durham VA Medical Center, NC',
    '279': 'Hampton VA Medical Center, VA',
    '280': 'Charles George VAMC, NC',
    '281': 'W.G. Hefner Salisbury VAMC, NC',
    '282': 'W.G. Hefner Salisbury VAMC, NC',
    '283': 'Fayetteville VA Medical Center, NC',
    '284': 'Fayetteville VA Medical Center, NC',
    '285': 'Durham VA Medical Center, NC',
    '286': 'Charles George VAMC, NC',
    '287': 'Charles George VAMC, NC',
    '288': 'Charles George VAMC, NC',
    '291': 'Wm. Jennings Bryan Dorn VAMC, SC',
    '292': 'Wm. Jennings Bryan Dorn VAMC, SC',
    '293': 'Wm. Jennings Bryan Dorn VAMC, SC',
    '294': 'Ralph H. Johnson VAMC, SC',
    '295': 'Ralph H. Johnson VAMC, SC',
    '296': 'Wm. Jennings Bryan Dorn VAMC, SC',
    '297': 'Wm. Jennings Bryan Dorn VAMC, SC',
    '298': 'Charlie A. Norwood VAMC, GA - Downtown Division',
    '299': 'Ralph H. Johnson VAMC, SC',
    '300': 'Joseph M. Cleland Atlanta VAMC, GA',
    '301': 'Joseph M. Cleland Atlanta VAMC, GA',
    '302': 'Joseph M. Cleland Atlanta VAMC, GA',
    '303': 'Joseph M. Cleland Atlanta VAMC, GA',
    '304': 'Charlie A. Norwood VAMC, GA - Downtown Division',
    '305': 'Joseph M. Cleland Atlanta VAMC, GA',
    '306': 'Charlie A. Norwood VAMC, GA - Downtown Division',
    '309': 'Charlie A. Norwood VAMC, GA - Downtown Division',
    '310': 'Carl Vinson VAMC, GA',
    '312': 'Carl Vinson VAMC, GA',
    '313': 'Ralph H. Johnson VAMC, SC',
    '314': 'Ralph H. Johnson VAMC, SC',
    '315': 'Ralph H. Johnson VAMC, SC',
    '316': 'Malcolm Randall Dept Of VAMC, FL',
    '317': 'Carl Vinson VAMC, GA',
    '319': 'Montgomery VA Medical Center, AL',
    '320': 'Malcolm Randall Dept Of VAMC, FL',
    '321': 'Malcolm Randall Dept Of VAMC, FL',
    '322': 'Malcolm Randall Dept Of VAMC, FL',
    '323': 'Malcolm Randall Dept Of VAMC, FL',
    '324': 'Biloxi VA Medical Center, MS',
    '325': 'Biloxi VA Medical Center, MS',
    '326': 'Malcolm Randall Dept Of VAMC, FL',
    '327': 'Orlando VA Medical Center, FL',
    '328': 'Orlando VA Medical Center, FL',
    '329': 'West Palm Beach VAMC, FL',
    '330': 'Bruce W. Carter Dept Of VAMC, FL',
    '331': 'Bruce W. Carter Dept Of VAMC, FL',
    '333': 'Bruce W. Carter Dept Of VAMC, FL',
    '334': 'West Palm Beach VAMC, FL',
    '335': 'James A. Haley Veterans Hosp, FL',
    '336': 'James A. Haley Veterans Hosp, FL',
    '337': 'C.W. Bill Young Dept Of VAMC, FL',
    '338': 'C.W. Bill Young Dept Of VAMC, FL',
    '339': 'C.W. Bill Young Dept Of VAMC, FL',
    '341': 'C.W. Bill Young Dept Of VAMC, FL',
    '342': 'C.W. Bill Young Dept Of VAMC, FL',
    '344': 'Malcolm Randall Dept Of VAMC, FL',
    '346': 'James A. Haley Veterans Hosp, FL',
    '347': 'Orlando VA Medical Center, FL',
    '349': 'West Palm Beach VAMC, FL',
    '350': 'Birmingham VA Medical Center, AL',
    '352': 'Birmingham VA Medical Center, AL',
    '354': 'Tuscaloosa VA Medical Center, AL',
    '355': 'Birmingham VA Medical Center, AL',
    '356': 'Birmingham VA Medical Center, AL',
    '358': 'Birmingham VA Medical Center, AL',
    '359': 'Birmingham VA Medical Center, AL',
    '360': 'Montgomery VA Medical Center, AL',
    '361': 'Montgomery VA Medical Center, AL',
    '362': 'Birmingham VA Medical Center, AL',
    '363': 'Montgomery VA Medical Center, AL',
    '364': 'Montgomery VA Medical Center, AL',
    '366': 'Biloxi VA Medical Center, MS',
    '367': 'Tuscaloosa VA Medical Center, AL',
    '370': 'Nashville VA Medical Center, TN',
    '371': 'Nashville VA Medical Center, TN',
    '372': 'Nashville VA Medical Center, TN',
    '373': 'Nashville VA Medical Center, TN',
    '374': 'Nashville VA Medical Center, TN',
    '376': 'James H. Quillen VAMC, TN',
    '377': 'James H. Quillen VAMC, TN',
    '378': 'James H. Quillen VAMC, TN',
    '379': 'James H. Quillen VAMC, TN',
    '380': 'LT COL Luke Weathers Jr VAMC, TN',
    '381': 'LT COL Luke Weathers Jr VAMC, TN',
    '383': 'LT COL Luke Weathers Jr VAMC, TN',
    '384': 'Nashville VA Medical Center, TN',
    '385': 'Nashville VA Medical Center, TN',
    '386': 'LT COL Luke Weathers Jr VAMC, TN',
    '387': 'G.V. (Sonny) Montgomery VAMC, MS',
    '388': 'LT COL Luke Weathers Jr VAMC, TN',
    '390': 'G.V. (Sonny) Montgomery VAMC, MS',
    '391': 'G.V. (Sonny) Montgomery VAMC, MS',
    '392': 'G.V. (Sonny) Montgomery VAMC, MS',
    '393': 'G.V. (Sonny) Montgomery VAMC, MS',
    '394': 'G.V. (Sonny) Montgomery VAMC, MS',
    '395': 'Biloxi VA Medical Center, MS',
    '396': 'G.V. (Sonny) Montgomery VAMC, MS',
    '397': 'G.V. (Sonny) Montgomery VAMC, MS',
    '401': 'Robley Rex VAMC, KY',
    '402': 'Robley Rex VAMC, KY',
    '403': 'Franklin R. Sousley Campus, KY',
    '404': 'Franklin R. Sousley Campus, KY',
    '405': 'Franklin R. Sousley Campus, KY',
    '410': 'Cincinnati VA Medical Center, OH',
    '416': 'Hershel Woody Williams VAMC, WV',
    '417': 'Franklin R. Sousley Campus, KY',
    '420': 'John J. Cochran VAMC, MO',
    '421': 'Nashville VA Medical Center, TN',
    '422': 'Nashville VA Medical Center, TN',
    '423': 'John J. Cochran VAMC, MO',
    '424': 'John J. Cochran VAMC, MO',
    '425': 'Franklin R. Sousley Campus, KY',
    '427': 'Robley Rex VAMC, KY',
    '430': 'Chalmers P. Wylie Veterans OC, OH',
    '431': 'Chillicothe VA Medical Center, OH',
    '432': 'Chalmers P. Wylie Veterans OC, OH',
    '433': 'Chalmers P. Wylie Veterans OC, OH',
    '435': 'Marion VA Medical Center, IN',
    '436': 'LTC Charles S Kettles VAMC, MI',
    '437': 'Chillicothe VA Medical Center, OH',
    '439': 'Louis Stokes Cleveland VAMC, OH',
    '440': 'Louis Stokes Cleveland VAMC, OH',
    '441': 'Louis Stokes Cleveland VAMC, OH',
    '442': 'Louis Stokes Cleveland VAMC, OH',
    '443': 'Louis Stokes Cleveland VAMC, OH',
    '444': 'Louis Stokes Cleveland VAMC, OH',
    '445': 'Louis Stokes Cleveland VAMC, OH',
    '446': 'Louis Stokes Cleveland VAMC, OH',
    '447': 'Louis Stokes Cleveland VAMC, OH',
    '448': 'Louis Stokes Cleveland VAMC, OH',
    '449': 'Louis Stokes Cleveland VAMC, OH',
    '450': 'Cincinnati VA Medical Center, OH',
    '451': 'Chillicothe VA Medical Center, OH',
    '452': 'Cincinnati VA Medical Center, OH',
    '454': 'Dayton VA Medical Center, OH',
    '455': 'Dayton VA Medical Center, OH',
    '456': 'Chillicothe VA Medical Center, OH',
    '457': 'Chillicothe VA Medical Center, OH',
    '458': 'LTC Charles S Kettles VAMC, MI',
    '461': 'Richard L. Roudebush VAMC, IN',
    '462': 'Richard L. Roudebush VAMC, IN',
    '463': 'Jesse Brown VAMC, IL',
    '465': 'Marion VA Medical Center, IN',
    '467': 'Marion VA Medical Center, IN',
    '468': 'Marion VA Medical Center, IN',
    '469': 'Marion VA Medical Center, IN',
    '470': 'Cincinnati VA Medical Center, OH',
    '471': 'Robley Rex VAMC, KY',
    '473': 'Dayton VA Medical Center, OH',
    '474': 'Richard L. Roudebush VAMC, IN',
    '475': 'John J. Cochran VAMC, MO',
    '477': 'John J. Cochran VAMC, MO',
    '478': 'Richard L. Roudebush VAMC, IN',
    '479': 'Richard L. Roudebush VAMC, IN',
    '480': 'John D. Dingell VAMC, MI',
    '481': 'LTC Charles S Kettles VAMC, MI',
    '482': 'John D. Dingell VAMC, MI',
    '483': 'John D. Dingell VAMC, MI',
    '484': 'Aleda E. Lutz VAMC, MI',
    '485': 'LTC Charles S Kettles VAMC, MI',
    '486': 'Aleda E. Lutz VAMC, MI',
    '487': 'Aleda E. Lutz VAMC, MI',
    '488': 'LTC Charles S Kettles VAMC, MI',
    '489': 'Battle Creek VA Medical Center, MI',
    '490': 'Battle Creek VA Medical Center, MI',
    '492': 'LTC Charles S Kettles VAMC, MI',
    '494': 'Battle Creek VA Medical Center, MI',
    '495': 'Battle Creek VA Medical Center, MI',
    '496': 'Aleda E. Lutz VAMC, MI',
    '497': 'Oscar G. Johnson VAMC, MI',
    '498': 'Oscar G. Johnson VAMC, MI',
    '499': 'Oscar G. Johnson VAMC, MI',
    '501': 'Omaha VA Medical Center, NE',
    '503': 'Omaha VA Medical Center, NE',
    '504': 'Omaha VA Medical Center, NE',
    '505': 'Omaha VA Medical Center, NE',
    '507': 'Omaha VA Medical Center, NE',
    '513': 'Royal C. Johnson VAMC, SD',
    '514': 'Omaha VA Medical Center, NE',
    '516': 'Omaha VA Medical Center, NE',
    '520': 'Omaha VA Medical Center, NE',
    '521': 'Omaha VA Medical Center, NE',
    '522': 'Omaha VA Medical Center, NE',
    '524': 'Omaha VA Medical Center, NE',
    '525': 'Omaha VA Medical Center, NE',
    '526': 'Omaha VA Medical Center, NE',
    '528': 'Omaha VA Medical Center, NE',
    '530': 'Clement J. Zablocki VAMC, WI',
    '531': 'Chicago, IL (North VAMC)',
    '532': 'Clement J. Zablocki VAMC, WI',
    '535': 'William S. Middleton Mem Hosp, WI',
    '537': 'William S. Middleton Mem Hosp, WI',
    '539': 'William S. Middleton Mem Hosp, WI',
    '543': 'Clement J. Zablocki VAMC, WI',
    '544': 'Tomah VA Medical Center, WI',
    '545': 'Oscar G. Johnson VAMC, MI',
    '546': 'Tomah VA Medical Center, WI',
    '547': 'Minneapolis VA Medical Center, MN',
    '548': 'Minneapolis VA Medical Center, MN',
    '549': 'Clement J. Zablocki VAMC, WI',
    '551': 'Minneapolis VA Medical Center, MN',
    '553': 'Minneapolis VA Medical Center, MN',
    '554': 'Minneapolis VA Medical Center, MN',
    '557': 'Minneapolis VA Medical Center, MN',
    '559': 'Minneapolis VA Medical Center, MN',
    '560': 'Minneapolis VA Medical Center, MN',
    '562': 'St. Cloud VA Medical Center, MN',
    '563': 'St. Cloud VA Medical Center, MN',
    '564': 'St. Cloud VA Medical Center, MN',
    '565': 'Fargo VA Medical Center, ND',
    '566': 'Fargo VA Medical Center, ND',
    '570': 'Royal C. Johnson VAMC, SD',
    '571': 'Royal C. Johnson VAMC, SD',
    '572': 'Royal C. Johnson VAMC, SD',
    '573': 'Royal C. Johnson VAMC, SD',
    '574': 'Royal C. Johnson VAMC, SD',
    '575': 'Fort Meade VA Medical Center, SD',
    '576': 'Fort Meade VA Medical Center, SD',
    '577': 'Fort Meade VA Medical Center, SD',
    '581': 'Fargo VA Medical Center, ND',
    '582': 'Fargo VA Medical Center, ND',
    '583': 'Fargo VA Medical Center, ND',
    '584': 'Fargo VA Medical Center, ND',
    '585': 'Fargo VA Medical Center, ND',
    '586': 'Fargo VA Medical Center, ND',
    '587': 'Fargo VA Medical Center, ND',
    '588': 'Fargo VA Medical Center, ND',
    '591': 'Fort Harrison Medical Center, MT',
    '592': 'Fort Harrison Medical Center, MT',
    '593': 'Fort Harrison Medical Center, MT',
    '594': 'Fort Harrison Medical Center, MT',
    '595': 'Fort Harrison Medical Center, MT',
    '596': 'Fort Harrison Medical Center, MT',
    '597': 'Fort Harrison Medical Center, MT',
    '598': 'Fort Harrison Medical Center, MT',
    '599': 'Fort Harrison Medical Center, MT',
    '600': 'Chicago, IL (North VAMC)',
    '601': 'Edward Hines Junior Hospital, IL',
    '602': 'Chicago, IL (North VAMC)',
    '604': 'Jesse Brown VAMC, IL',
    '605': 'Edward Hines Junior Hospital, IL',
    '606': 'Jesse Brown VAMC, IL',
    '609': 'Edward Hines Junior Hospital, IL',
    '610': 'William S. Middleton Mem Hosp, WI',
    '611': 'William S. Middleton Mem Hosp, WI',
    '613': 'Edward Hines Junior Hospital, IL',
    '614': 'Omaha VA Medical Center, NE',
    '616': 'Danville VA Medical Center, IL',
    '617': 'Danville VA Medical Center, IL',
    '618': 'Danville VA Medical Center, IL',
    '619': 'Danville VA Medical Center, IL',
    '622': 'John J. Cochran VAMC, MO',
    '623': 'Omaha VA Medical Center, NE',
    '624': 'John J. Cochran VAMC, MO',
    '625': 'Danville VA Medical Center, IL',
    '627': 'Danville VA Medical Center, IL',
    '628': 'John J. Cochran VAMC, MO',
    '629': 'John J. Cochran VAMC, MO',
    '630': 'John J. Cochran VAMC, MO',
    '631': 'John J. Cochran VAMC, MO',
    '633': 'John J. Cochran VAMC, MO',
    '635': 'Kansas City VA Medical Center, MO',
    '636': 'John J. Cochran VAMC, MO',
    '637': 'John J. Cochran VAMC, MO',
    '638': 'John J. Cochran VAMC, MO',
    '639': 'John J. Cochran VAMC, MO',
    '640': 'Kansas City VA Medical Center, MO',
    '641': 'Kansas City VA Medical Center, MO',
    '644': 'Kansas City VA Medical Center, MO',
    '645': 'Kansas City VA Medical Center, MO',
    '647': 'Kansas City VA Medical Center, MO',
    '648': 'Fayetteville VA Medical Center, AR',
    '650': 'Kansas City VA Medical Center, MO',
    '651': 'Kansas City VA Medical Center, MO',
    '652': 'Kansas City VA Medical Center, MO',
    '653': 'Kansas City VA Medical Center, MO',
    '654': 'Kansas City VA Medical Center, MO',
    '655': 'Kansas City VA Medical Center, MO',
    '656': 'Fayetteville VA Medical Center, AR',
    '657': 'Kansas City VA Medical Center, MO',
    '658': 'Fayetteville VA Medical Center, AR',
    '660': 'Kansas City VA Medical Center, MO',
    '661': 'Kansas City VA Medical Center, MO',
    '662': 'Kansas City VA Medical Center, MO',
    '664': 'Kansas City VA Medical Center, MO',
    '666': 'Kansas City VA Medical Center, MO',
    '667': 'Kansas City VA Medical Center, MO',
    '672': 'Kansas City VA Medical Center, MO',
    '673': 'Kansas City VA Medical Center, MO',
    '674': 'Kansas City VA Medical Center, MO',
    '675': 'Kansas City VA Medical Center, MO',
    '676': 'Kansas City VA Medical Center, MO',
    '678': 'Kansas City VA Medical Center, MO',
    '680': 'Omaha VA Medical Center, NE',
    '681': 'Omaha VA Medical Center, NE',
    '685': 'Omaha VA Medical Center, NE',
    '687': 'Omaha VA Medical Center, NE',
    '688': 'Omaha VA Medical Center, NE',
    '689': 'Omaha VA Medical Center, NE',
    '691': 'Cheyenne VA Medical Center, WY',
    '693': 'Fort Meade VA Medical Center, SD',
    '700': 'New Orleans VA Medical Center, LA',
    '701': 'New Orleans VA Medical Center, LA',
    '703': 'New Orleans VA Medical Center, LA',
    '704': 'New Orleans VA Medical Center, LA',
    '705': 'Alexandria VA Medical Center, LA',
    '706': 'Alexandria VA Medical Center, LA',
    '708': 'New Orleans VA Medical Center, LA',
    '711': 'Overton Brooks VAMC, LA',
    '712': 'Overton Brooks VAMC, LA',
    '713': 'Alexandria VA Medical Center, LA',
    '714': 'Alexandria VA Medical Center, LA',
    '716': 'John L. McClellan Mem Vet Hosp, AR',
    '717': 'John L. McClellan Mem Vet Hosp, AR',
    '719': 'John L. McClellan Mem Vet Hosp, AR',
    '720': 'John L. McClellan Mem Vet Hosp, AR',
    '721': 'John L. McClellan Mem Vet Hosp, AR',
    '722': 'John L. McClellan Mem Vet Hosp, AR',
    '723': 'LT COL Luke Weathers Jr VAMC, TN',
    '724': 'LT COL Luke Weathers Jr VAMC, TN',
    '726': 'Fayetteville VA Medical Center, AR',
    '727': 'Fayetteville VA Medical Center, AR',
    '728': 'John L. McClellan Mem Vet Hosp, AR',
    '729': 'Fayetteville VA Medical Center, AR',
    '730': 'Oklahoma City VAMC, OK',
    '731': 'Oklahoma City VAMC, OK',
    '734': 'Oklahoma City VAMC, OK',
    '735': 'Oklahoma City VAMC, OK',
    '736': 'Oklahoma City VAMC, OK',
    '737': 'Oklahoma City VAMC, OK',
    '740': 'Jack C. Montgomery VAMC, OK',
    '741': 'Jack C. Montgomery VAMC, OK',
    '743': 'Fayetteville VA Medical Center, AR',
    '744': 'Jack C. Montgomery VAMC, OK',
    '745': 'Jack C. Montgomery VAMC, OK',
    '746': 'Oklahoma City VAMC, OK',
    '747': 'Jack C. Montgomery VAMC, OK',
    '748': 'Oklahoma City VAMC, OK',
    '750': 'Dallas VA Medical Center, TX',
    '752': 'Dallas VA Medical Center, TX',
    '754': 'Dallas VA Medical Center, TX',
    '755': 'Overton Brooks VAMC, LA',
    '756': 'Overton Brooks VAMC, LA',
    '757': 'Dallas VA Medical Center, TX',
    '758': 'Olin E. Teague Vet Center, TX',
    '759': 'Michael E. DeBakey VAMC, TX',
    '760': 'Dallas VA Medical Center, TX',
    '761': 'Dallas VA Medical Center, TX',
    '762': 'Dallas VA Medical Center, TX',
    '763': 'Oklahoma City VAMC, OK',
    '765': 'Olin E. Teague Vet Center, TX',
    '767': 'Olin E. Teague Vet Center, TX',
    '768': 'Olin E. Teague Vet Center, TX',
    '769': 'George H. O\'Brien, Jr., VAMC, TX',
    '770': 'Michael E. DeBakey VAMC, TX',
    '773': 'Michael E. DeBakey VAMC, TX',
    '774': 'Michael E. DeBakey VAMC, TX',
    '775': 'Michael E. DeBakey VAMC, TX',
    '777': 'Michael E. DeBakey VAMC, TX',
    '778': 'Olin E. Teague Vet Center, TX',
    '779': 'Audie L. Murphy Mem Vet Hosp, TX',
    '780': 'Audie L. Murphy Mem Vet Hosp, TX',
    '781': 'Audie L. Murphy Mem Vet Hosp, TX',
    '782': 'Audie L. Murphy Mem Vet Hosp, TX',
    '784': 'Harlingen VA Clinic, TX',
    '785': 'Harlingen VA Clinic, TX',
    '786': 'Olin E. Teague Vet Center, TX',
    '787': 'Olin E. Teague Vet Center, TX',
    '789': 'Olin E. Teague Vet Center, TX',
    '790': 'Thomas E. Creek VAMC, TX',
    '791': 'Thomas E. Creek VAMC, TX',
    '792': 'Thomas E. Creek VAMC, TX',
    '794': 'Thomas E. Creek VAMC, TX',
    '796': 'George H. O\'Brien, Jr., VAMC, TX',
    '797': 'George H. O\'Brien, Jr., VAMC, TX',
    '799': 'El Paso VA Clinic, TX',
    '800': 'Rocky Mountain Regional VAMC, CO',
    '802': 'Rocky Mountain Regional VAMC, CO',
    '804': 'Rocky Mountain Regional VAMC, CO',
    '805': 'Cheyenne VA Medical Center, WY',
    '807': 'Cheyenne VA Medical Center, WY',
    '808': 'Rocky Mountain Regional VAMC, CO',
    '809': 'Rocky Mountain Regional VAMC, CO',
    '810': 'Rocky Mountain Regional VAMC, CO',
    '811': 'Rocky Mountain Regional VAMC, CO',
    '812': 'Rocky Mountain Regional VAMC, CO',
    '813': 'Raymond G. Murphy VAMC, NM',
    '814': 'Grand Junction VAMC, CO',
    '815': 'Grand Junction VAMC, CO',
    '816': 'Grand Junction VAMC, CO',
    '820': 'Cheyenne VA Medical Center, WY',
    '822': 'Cheyenne VA Medical Center, WY',
    '823': 'Cheyenne VA Medical Center, WY',
    '824': 'Sheridan VA Medical Center, WY',
    '825': 'Sheridan VA Medical Center, WY',
    '826': 'Sheridan VA Medical Center, WY',
    '827': 'Fort Meade VA Medical Center, SD',
    '828': 'Sheridan VA Medical Center, WY',
    '829': 'Sheridan VA Medical Center, WY',
    '831': 'Sheridan VA Medical Center, WY',
    '832': 'George E. Wahlen VAMC, UT',
    '833': 'Boise VA Medical Center, ID',
    '834': 'Boise VA Medical Center, ID',
    '835': 'Jonathan M. Wainwright VAMC, WA',
    '836': 'Boise VA Medical Center, ID',
    '837': 'Boise VA Medical Center, ID',
    '838': 'Mann-Grandstaff VAMC, WA',
    '840': 'George E. Wahlen VAMC, UT',
    '841': 'George E. Wahlen VAMC, UT',
    '843': 'George E. Wahlen VAMC, UT',
    '844': 'George E. Wahlen VAMC, UT',
    '845': 'Grand Junction VAMC, CO',
    '847': 'George E. Wahlen VAMC, UT',
    '850': 'Carl T. Hayden VAMC, AZ',
    '851': 'Tucson VA Medical Center, AZ',
    '852': 'Carl T. Hayden VAMC, AZ',
    '853': 'Carl T. Hayden VAMC, AZ',
    '855': 'Carl T. Hayden VAMC, AZ',
    '856': 'Tucson VA Medical Center, AZ',
    '857': 'Tucson VA Medical Center, AZ',
    '859': 'Carl T. Hayden VAMC, AZ',
    '860': 'Bob Stump VAMC, AZ',
    '863': 'Bob Stump VAMC, AZ',
    '864': 'Bob Stump VAMC, AZ',
    '865': 'Bob Stump VAMC, AZ',
    '871': 'Raymond G. Murphy VAMC, NM',
    '873': 'Raymond G. Murphy VAMC, NM',
    '874': 'Raymond G. Murphy VAMC, NM',
    '875': 'Raymond G. Murphy VAMC, NM',
    '877': 'Raymond G. Murphy VAMC, NM',
    '879': 'Raymond G. Murphy VAMC, NM',
    '880': 'Raymond G. Murphy VAMC, NM',
    '881': 'Thomas E. Creek VAMC, TX',
    '882': 'Raymond G. Murphy VAMC, NM',
    '883': 'Raymond G. Murphy VAMC, NM',
    '884': 'Raymond G. Murphy VAMC, NM',
    '890': 'North Las Vegas VA Medical Center, NV',
    '891': 'North Las Vegas VA Medical Center, NV',
    '894': 'Ioannis A. Lougaris VAMC, NV',
    '895': 'Ioannis A. Lougaris VAMC, NV',
    '898': 'George E. Wahlen VAMC, UT',
    '900': 'West Los Angeles VAMC, CA',
    '902': 'Tibor Rubin VA Medical Center, CA',
    '906': 'Tibor Rubin VA Medical Center, CA',
    '908': 'Tibor Rubin VA Medical Center, CA',
    '910': 'West Los Angeles VAMC, CA',
    '913': 'West Los Angeles VAMC, CA',
    '917': 'Jerry L. Pettis Mem Vet Hosp, CA',
    '919': 'Jennifer Moreno VAMC, CA',
    '920': 'Jennifer Moreno VAMC, CA',
    '921': 'Jennifer Moreno VAMC, CA',
    '922': 'Jerry L. Pettis Mem Vet Hosp, CA',
    '923': 'Jerry L. Pettis Mem Vet Hosp, CA',
    '925': 'Jerry L. Pettis Mem Vet Hosp, CA',
    '926': 'Tibor Rubin VA Medical Center, CA',
    '927': 'Tibor Rubin VA Medical Center, CA',
    '928': 'Tibor Rubin VA Medical Center, CA',
    '930': 'West Los Angeles VAMC, CA',
    '931': 'West Los Angeles VAMC, CA',
    '932': 'Fresno VA Medical Center, CA',
    '933': 'West Los Angeles VAMC, CA',
    '934': 'West Los Angeles VAMC, CA',
    '935': 'West Los Angeles VAMC, CA',
    '936': 'Fresno VA Medical Center, CA',
    '937': 'Fresno VA Medical Center, CA',
    '939': 'Palo Alto VA Medical Center, CA',
    '940': 'Palo Alto VA Medical Center, CA',
    '941': 'San Francisco VAMC, CA',
    '943': 'Palo Alto VA Medical Center, CA',
    '945': 'Northern California HCS, CA',
    '946': 'San Francisco VAMC, CA',
    '950': 'Palo Alto VA Medical Center, CA',
    '951': 'Palo Alto VA Medical Center, CA',
    '952': 'Northern California HCS, CA',
    '953': 'Fresno VA Medical Center, CA',
    '954': 'San Francisco VAMC, CA',
    '955': 'San Francisco VAMC, CA',
    '956': 'Northern California HCS, CA',
    '959': 'Northern California HCS, CA',
    '960': 'Northern California HCS, CA',
    '961': 'Ioannis A. Lougaris VAMC, NV',
    '967': 'Spark M. Matsunaga VAMC, HI',
    '968': 'Spark M. Matsunaga VAMC, HI',
    '969': 'Spark M. Matsunaga VAMC, HI',
    '970': 'Portland VA Medical Center, OR',
    '971': 'Portland VA Medical Center, OR',
    '972': 'Portland VA Medical Center, OR',
    '973': 'Portland VA Medical Center, OR',
    '974': 'Roseburg VA Medical Center, OR',
    '975': 'White City VA Medical Center, OR',
    '976': 'White City VA Medical Center, OR',
    '977': 'Boise VA Medical Center, ID',
    '978': 'Jonathan M. Wainwright VAMC, WA',
    '980': 'Seattle VA Medical Center, WA',
    '981': 'Seattle VA Medical Center, WA',
    '982': 'Seattle VA Medical Center, WA',
    '983': 'Seattle VA Medical Center, WA',
    '984': 'Seattle VA Medical Center, WA',
    '985': 'Seattle VA Medical Center, WA',
    '986': 'Portland VA Medical Center, OR',
    '988': 'Mann-Grandstaff VAMC, WA',
    '989': 'Jonathan M. Wainwright VAMC, WA',
    '992': 'Mann-Grandstaff VAMC, WA',
    '993': 'Jonathan M. Wainwright VAMC, WA',
    '995': 'Col Rasmuson Campus Ak VAHCS, AK',
    '996': 'Col Rasmuson Campus Ak VAHCS, AK',
    '997': 'Col Rasmuson Campus Ak VAHCS, AK',
    '998': 'Col Rasmuson Campus Ak VAHCS, AK',
}
